### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by Namatuzio** [Amir-Helali/Txt2StaticHtml#2]
I want to add MD support to your solution! 

I was thinking it would be nice to be able to feed Txt2StaticHtml a markdown file and allow it to process certain markdown features, such as headings and links translating them 1:1 with their HTML counterparts.

**Comment by Amir-Helali** [comment]
After going over the changes you made in call with you, please make the following updates to the pull request:

1. 1 if statement is missing where the condition for checking file extension is .md or not.
2. Please have <h1> be only 1 and to the top of the body.
3. Please revert back example 2 to the previous file, as this was used to demo the style sheet functionality of the program.
4. When a file was converted the original extension is still part of the converted extension. Please remove that.
5. Duplication inside the TextToHtmlConverter to create html conten. Please fix that.
