### ISSUE TITLE
Add TOML support for -c/--config switch

### ISSUE THREAD

**Issue by bryce-seefieldt** [Amir-Helali/Txt2StaticHtml#7]
Provide config file support to user

**Comment by bryce-seefieldt** [comment]
Hi @Amir-Helali - I apologize but I am closing this issue without a pull request.
Under the time constraints I amstruggling to integrate the logic to support the -c/--config switch into the current program.cs file.  In my opinion, or at least to my level of comprehension, the current if/else structure is going to require quite a bit of restructuring to be able to support the addition of the -c switch.
I'd be happy to work on it with you going forward outside the framework of Lab4.

**Comment by Amir-Helali** [comment]
Hi @bryce-seefieldt. No worries, I agree and I do believe that the current conditional statements can be simplified, I just need to find the time to clean it up a bit. I'd be happy to have your contribution to this project for the future, if you are interested.
